Add regression test of let_cxx_string in async fn
    error: future cannot be sent between threads safely
      --> tests/cxx_string.rs:14:5
       |
    13 |     fn assert_send(_: impl Send) {}
       |                            ---- required by this bound in `assert_send`
    14 |     assert_send(f());
       |     ^^^^^^^^^^^ future returned by `f` is not `Send`
       |
       = help: within `impl Future`, the trait `Send` is not implemented for `*const ()`
    note: future is not `Send` as this value is used across an await
      --> tests/cxx_string.rs:9:9
       |
    6  |         let_cxx_string!(s = "...");
       |         --------------------------- has type `StackString` which is not `Send`
    ...
    9  |         g(&s).await;
       |         ^^^^^^^^^^^ await occurs here, with `mut $var` maybe used later
    10 |     }
       |     - `mut $var` is later dropped here