Pass through cfg attrs
Otherwise things like cfg(target_os = "android") cannot be used
within a cxx bridge.

Resolves error:
error: unsupported attribute
 --> system/bt/gd/rust/common/src/sys_prop.rs:4:1
  |
4 | #[cfg(target_os = "android")]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

When updating to cxx version 1.0.x in AOSP.
https://cs.android.com/android/platform/superproject/+/master:system/bt/gd/rust/common/src/sys_prop.rs;l=3