Ignore Windows CI until VS 17.6.2 detection is fixed
    Extracting Bazel installation...
    Starting local Bazel server and connecting to it...
    INFO: Analyzed target //demo:demo (100 packages loaded, 1724 targets configured).
    INFO: Found 1 target...
    ERROR: D:/a/cxx/cxx/BUILD:47:11: Compiling src/cxx.cc failed: (Exit 1): vc_installation_error_x64.bat failed: error executing command (from target //:core-lib)
      cd /d C:/users/runneradmin/_bazel_runneradmin/dzh43mlk/execroot/cxx.rs
      SET INCLUDE=msvc_not_found
        SET PATH=msvc_not_found
        SET ***
        SET RUNFILES_MANIFEST_ONLY=1
        SET TEMP=msvc_not_found
        SET TMP=msvc_not_found
      external\local_config_cc\vc_installation_error_x64.bat /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /bigobj /Zm500 /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /I. /Ibazel-out/x64_windows-fastbuild/bin /DBAZEL_CURRENT_REPOSITORY="" /showIncludes /MD /Od /Z7 /wd4117 -D__DATE__="redacted" -D__TIMESTAMP__="redacted" -D__TIME__="redacted" /Fobazel-out/x64_windows-fastbuild/bin/_objs/core-lib/cxx.obj /c src/cxx.cc
    # Configuration: e0798f7914b351221e8e2203796f66e692ef40426e8a590aad75aebda6338ccc
    # Execution platform: @local_config_platform//:host

    The target you are compiling requires Visual C++ build tools.
    Bazel couldn't find a valid Visual C++ build tools installation on your machine.

    Visual C++ build tools seems to be installed at C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC
    But Bazel can't find the following tools:
        VCVARSALL.BAT, cl.exe, link.exe, lib.exe, ml64.exe
    for x64 target architecture

    Please check your installation following https://bazel.build/docs/windows#using

    Target //demo:demo failed to build
    INFO: Elapsed time: 36.579s, Critical Path: 0.68s
    INFO: 59 processes: 59 internal.
    ERROR: Build failed. Not running target