Fix "Rules should not declare an attribute named metadata"
    From `load` at implicit location

    Caused by:
        0: From `load` at tools/buck/prelude/prelude.bzl:8:6-29
        1: From `load` at tools/buck/prelude/native.bzl:28:6-18
        2: Error evaluating module: `prelude//rules.bzl`
        3: Traceback (most recent call last):
             * tools/buck/prelude/rules.bzl:118, in <module>
                 rules = {rule.name: _mk_rule(rule) for rule in _declared_rules.values()}
             * tools/buck/prelude/rules.bzl:76, in _mk_rule
                 return rule(
           error: Rules should not declare an attribute named metadata`
             --> tools/buck/prelude/rules.bzl:76:12
              |
           76 |       return rule(
              |  ____________^
           77 | |         impl = impl,
           78 | |         attrs = attributes,
           79 | |         is_configuration_rule = name in _config_implemented_rules,
           80 | |         is_toolchain_rule = name in toolchain_rule_names,
           81 | |         **extra_args
           82 | |     )
              | |_____^
              |