Test undefined and private classes
Undefined:

    /usr/include/c++/bits/shared_ptr_base.h: In instantiation of 'std::__shared_ptr<_Tp, _Lp>::__shared_ptr(_Yp*) [with _Yp = tests::Undefined; <template-parameter-2-2> = void; _Tp = tests::Undefined; __gnu_cxx::_Lock_policy _Lp = __gnu_cxx::_S_atomic]':
    /usr/include/c++/bits/shared_ptr.h:214:46:   required from 'std::shared_ptr<_Tp>::shared_ptr(_Yp*) [with _Yp = tests::Undefined; <template-parameter-2-2> = void; _Tp = tests::Undefined]'
    target/debug/build/cxx-test-suite-52adc32e0986ae77/out/cxxbridge/sources/tests/ffi/lib.rs.cc:2740:56:   required from here
    /usr/include/c++/bits/shared_ptr_base.h:1472:26: error: invalid application of 'sizeof' to incomplete type 'tests::Undefined'
     1472 |           static_assert( sizeof(_Yp) > 0, "incomplete type" );
          |                          ^~~~~~~~~~~

Private:

    /usr/include/c++/bits/shared_ptr_base.h: In instantiation of 'std::__shared_count<_Lp>::__shared_count(_Ptr) [with _Ptr = tests::Private*; __gnu_cxx::_Lock_policy _Lp = __gnu_cxx::_S_atomic]':
    /usr/include/c++/bits/shared_ptr_base.h:928:22:   required from 'std::__shared_count<_Lp>::__shared_count(_Ptr, std::false_type) [with _Ptr = tests::Private*; __gnu_cxx::_Lock_policy _Lp = __gnu_cxx::_S_atomic; std::false_type = std::integral_constant<bool, false>]'
    /usr/include/c++/bits/shared_ptr_base.h:1469:17:   required from 'std::__shared_ptr<_Tp, _Lp>::__shared_ptr(_Yp*) [with _Yp = tests::Private; <template-parameter-2-2> = void; _Tp = tests::Private; __gnu_cxx::_Lock_policy _Lp = __gnu_cxx::_S_atomic]'
    /usr/include/c++/bits/shared_ptr.h:214:46:   required from 'std::shared_ptr<_Tp>::shared_ptr(_Yp*) [with _Yp = tests::Private; <template-parameter-2-2> = void; _Tp = tests::Private]'
    target/debug/build/cxx-test-suite-52adc32e0986ae77/out/cxxbridge/sources/tests/ffi/lib.rs.cc:2758:54:   required from here
    /usr/include/c++/bits/shared_ptr_base.h:921:15: error: 'tests::Private::~Private()' is private within this context
      921 |               delete __p;
          |               ^~~~~~~~~~
    target/debug/build/cxx-test-suite-52adc32e0986ae77/out/cxxbridge/crate/tests/ffi/tests.h:41:3: note: declared private here
       41 |   ~Private();
          |   ^
    /usr/include/c++/bits/shared_ptr_base.h: In instantiation of 'void std::_Sp_counted_ptr<_Ptr, _Lp>::_M_dispose() [with _Ptr = tests::Private*; __gnu_cxx::_Lock_policy _Lp = __gnu_cxx::_S_atomic]':
    /usr/include/c++/bits/shared_ptr_base.h:427:7:   required from here
    /usr/include/c++/bits/shared_ptr_base.h:428:9: error: 'tests::Private::~Private()' is private within this context
      428 |       { delete _M_ptr; }
          |         ^~~~~~~~~~~~~
    target/debug/build/cxx-test-suite-52adc32e0986ae77/out/cxxbridge/crate/tests/ffi/tests.h:41:3: note: declared private here
       41 |   ~Private();
          |   ^