Move third-party crate root to a lib.rs file
Using /dev/null is no longer compatible with the most recent version of
Bazel's rules_rust crate_universe.

    INFO: Running command line: bazel-bin/third-party/vendor.sh
    Error: Package "third-party" target "third_party" had an absolute source path "/dev/null", which is not supported