Fix "User provided attribute `within_view` overrides internal attribute"
    From `load` at implicit location

    Caused by:
        0: From `load` at tools/buck/prelude/prelude.bzl:8:6-29
        1: From `load` at tools/buck/prelude/native.bzl:19:6-39
        2: Error evaluating module: `prelude//cxx/cxx_toolchain.bzl`
        3: Traceback (most recent call last):
             * tools/buck/prelude/cxx/cxx_toolchain.bzl:204, in <module>
                 cxx_toolchain_inheriting_target_platform = rule(
           error: User provided attribute `within_view` overrides internal attribute
              --> tools/buck/prelude/cxx/cxx_toolchain.bzl:204:44
               |
           204 |   cxx_toolchain_inheriting_target_platform = rule(
               |  ____________________________________________^
           205 | |     impl = cxx_toolchain_impl,
           206 | |     attrs = _cxx_toolchain_inheriting_target_platform_attrs(),
           207 | |     is_toolchain_rule = True,
           208 | | )
               | |_^
               |