Disable clippy CI due to clippy crash
Clippy crash: https://github.com/rust-lang/rust-clippy/issues/7423

    thread 'rustc' panicked at '`LateContext::typeck_results` called outside of body', src/tools/clippy/clippy_lints/src/use_self.rs:213:20
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

    error: internal compiler error: unexpected panic

    note: the compiler unexpectedly panicked. this is a bug.

    query stack during panic:
    #0 [analysis] running analysis passes on this crate
    end of query stack