Add reindeer fixup for clap_builder crate so it works in vendored mode
    Action failed: root//third-party:clap_builder-4.3.21 (rustc rlib-static-static-metadata/clap_builder-metadata rlib,static,metadata [diag])

    error: couldn't read buck-out/v2/gen/root/524f8da68ea2a374/third-party/__clap_builder-4.3.21__/__srcs/vendor/clap_builder-4.3.21/src/../README.md: No such file or directory (os error 2)
     --> third-party/vendor/clap_builder-4.3.21/src/lib.rs:7:10
      |
    7 | #![doc = include_str!("../README.md")]
      |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      |
      = note: this error originates in the macro `include_str` (in Nightly builds, run with -Z macro-backtrace for more info)