Fix unsafes in from_unmanaged FFI
    error: extern blocks should be unsafe
       --> tests/ffi/lib.rs:109:48
        |
    109 |         fn c_return_shared_ptr() -> SharedPtr<C>;
        |                                                ^
        |                                                |
        |                                                help: needs `unsafe` before the extern keyword: `unsafe`
        |
        = warning: this is accepted in the current edition (Rust 2021) but is a hard error in Rust 2024!
        = note: for more information, see <https://doc.rust-lang.org/edition-guide/rust-2024/unsafe-extern.html>
    note: the lint level is defined here
       --> tests/ffi/lib.rs:16:9
        |
     16 | #![deny(warnings)] // Check that expansion of `cxx::bridge` doesn't trigger warnings.
        |         ^^^^^^^^
        = note: `#[deny(missing_unsafe_on_extern)]` implied by `#[deny(warnings)]`

    error[E0133]: call to unsafe function `<ffi::C as cxx::memory::SharedPtrTarget>::__from_unmanaged::__from_unmanaged` is unsafe and requires unsafe block
       --> tests/ffi/lib.rs:109:48
        |
    109 |         fn c_return_shared_ptr() -> SharedPtr<C>;
        |                                                ^ call to unsafe function
        |
        = note: for more information, see <https://doc.rust-lang.org/edition-guide/rust-2024/unsafe-op-in-unsafe-fn.html>
        = note: consult the function's documentation for information on how to avoid undefined behavior
    note: an unsafe function restricts its caller, but its body is safe by default
       --> tests/ffi/lib.rs:109:48
        |
    109 |         fn c_return_shared_ptr() -> SharedPtr<C>;
        |                                                ^
    note: the lint level is defined here
       --> tests/ffi/lib.rs:15:11
        |
     15 | #![forbid(unsafe_op_in_unsafe_fn)]
        |           ^^^^^^^^^^^^^^^^^^^^^^