Add test of lifetime elision on type alias
Currently fails.

    error[E0106]: missing lifetime specifier
      --> tests/ffi/module.rs:17:54
       |
    17 |         fn c_lifetime_elision_member_fn(self: &C) -> &CxxVector<u8>;
       |                                                      ^ expected named lifetime parameter
       |
       = help: this function's return type contains a borrowed value, but there is no value for it to be borrowed from
    help: consider using the `'static` lifetime, but this is uncommon unless you're returning a borrowed value from a `const` or a `static`
       |
    17 |         fn c_lifetime_elision_member_fn(self: &C) -> &'static CxxVector<u8>;
       |                                                       +++++++
    help: instead, you are more likely to want to change the argument to be borrowed...
       |
    17 |         fn c_lifetime_elision_member_fn(self: &&C) -> &CxxVector<u8>;
       |                                               +
    help: ...or alternatively, you might want to return an owned value
       |
    17 -         fn c_lifetime_elision_member_fn(self: &C) -> &CxxVector<u8>;
    17 +         fn c_lifetime_elision_member_fn(self: &C) -> CxxVector<u8>;
       |

    error[E0106]: missing lifetime specifier
      --> tests/ffi/module.rs:18:44
       |
    18 |         fn c_lifetime_elision_fn(c: &C) -> &CxxVector<u8>;
       |                                            ^ expected named lifetime parameter
       |
       = help: this function's return type contains a borrowed value, but there is no value for it to be borrowed from
    help: consider using the `'static` lifetime, but this is uncommon unless you're returning a borrowed value from a `const` or a `static`
       |
    18 |         fn c_lifetime_elision_fn(c: &C) -> &'static CxxVector<u8>;
       |                                             +++++++
    help: instead, you are more likely to want to change the argument to be borrowed...
       |
    18 |         fn c_lifetime_elision_fn(c: &&C) -> &CxxVector<u8>;
       |                                     +
    help: ...or alternatively, you might want to return an owned value
       |
    18 -         fn c_lifetime_elision_fn(c: &C) -> &CxxVector<u8>;
    18 +         fn c_lifetime_elision_fn(c: &C) -> CxxVector<u8>;
       |