Add regression test for issue 1729
    test test_panic ... error: Undefined Behavior: reading memory at alloc71811[0x8..0x10], but memory is uninitialized at [0x8..0x10], and this operation requires initialized memory
       --> $RUSTUP_HOME/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/raw_vec/mod.rs:615:9
        |
    615 |         self.ptr.cast().as_non_null_ptr()
        |         ^^^^^^^^ Undefined Behavior occurred here
        |
        = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
        = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
        = note: this is on thread `test_panic`
        = note: stack backtrace:
                0: cxx::alloc::raw_vec::RawVecInner::non_null::<u8>
                    at $RUSTUP_HOME/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/raw_vec/mod.rs:615:9: 615:17
                1: cxx::alloc::raw_vec::RawVecInner::ptr::<u8>
                    at $RUSTUP_HOME/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/raw_vec/mod.rs:610:9: 610:29
                2: cxx::alloc::raw_vec::RawVec::<u8>::ptr
                    at $RUSTUP_HOME/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/raw_vec/mod.rs:296:9: 296:25
                3: std::vec::Vec::<u8>::as_mut_ptr
                    at $RUSTUP_HOME/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:2061:9: 2061:23
                4: <std::vec::Vec<u8> as std::ops::Drop>::drop
                    at $RUSTUP_HOME/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:4303:13: 4303:30
                5: std::ptr::drop_glue::<std::vec::Vec<u8>> - shim(Some(std::vec::Vec<u8>))
                    at $RUSTUP_HOME/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:825:1: 827:25
                6: std::ptr::drop_in_place::<std::vec::Vec<u8>>
                    at $RUSTUP_HOME/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:820:14: 820:38
                7: cxx::string::miri::string_destroy
                    at src/cxx_string.rs:361:13: 361:68
                8: <cxx::private::StackString as std::ops::Drop>::drop
                    at src/cxx_string.rs:328:13: 328:33
                9: std::ptr::drop_glue::<cxx::private::StackString> - shim(Some(cxx::private::StackString))
                    at $RUSTUP_HOME/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:825:1: 827:25
                10: test_panic::{closure#0}
                    at tests/cxx_string.rs:61:5: 61:6
                11: std::panicking::catch_unwind::do_call::<{closure@tests/cxx_string.rs:59:33: 59:35}, ()>
                    at $RUSTUP_HOME/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:576:43: 576:46
                12: std::panicking::catch_unwind::<(), {closure@tests/cxx_string.rs:59:33: 59:35}>
                    at $RUSTUP_HOME/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:544:19: 544:77
                13: std::panic::catch_unwind::<{closure@tests/cxx_string.rs:59:33: 59:35}, ()>
                    at $RUSTUP_HOME/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:359:14: 359:40
                14: test_panic
                    at tests/cxx_string.rs:59:13: 61:7
                15: test_panic::{closure#0}
                    at tests/cxx_string.rs:58:16: 58:16

    Uninitialized memory occurred at alloc71811[0x8..0x10], in this allocation:
    alloc71811 (stack variable, size: 64, align: 8) {
        0x00 │ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ │ ░░░░░░░░░░░░░░░░
        0x10 │ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ │ ░░░░░░░░░░░░░░░░
        0x20 │ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ │ ░░░░░░░░░░░░░░░░
        0x30 │ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ │ ░░░░░░░░░░░░░░░░
    }

    note: some details are omitted, run with `MIRIFLAGS=-Zmiri-backtrace=full` for a verbose backtrace

    error: aborting due to 1 previous error

    error: test failed, to rerun pass `--test cxx_string`

    Caused by:
      process didn't exit successfully: `$RUSTUP_HOME/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo-miri runner /git/cxx/target/miri/x86_64-unknown-linux-gnu/debug/deps/cxx_string-1446ab91331ab562` (exit status: 1)
    note: test exited abnormally; to see the full output pass --no-capture to the harness.