Temporarily disable buck2 CI on Windows
We need to improve the way that the system_cxx_toolchain discovers
location of the MSVC build tools.

    Action failed: root//:core (prelude//platforms:default#fb50fd37ce946800) (cxx_compile src/cxx.cc)
    Local command returned non-zero exit code 1
    Local command: "buck-out\\v2\\gen\\toolchains\\fb50fd37ce946800-fb50fd37ce946800\\__cxx__\\windows_compiler.bat" "/Fobuck-out\\v2\\gen\\root\\fb50fd37ce946800\\__core__\\__objects__\\src\\cxx.cc.obj" "@buck-out\\v2\\gen\\root\\fb50fd37ce946800\\__core__\\.cc.argsfile" -c "src\\cxx.cc"
    Stdout:
    Stderr: Traceback (most recent call last):
      File "D:\a\cxx\cxx\buck-out\v2\gen\prelude\fb50fd37ce946800\cxx\tools\__windows_compiler_wrapper__\windows_compiler_wrapper.py", line 59, in <module>
        main()
      File "D:\a\cxx\cxx\buck-out\v2\gen\prelude\fb50fd37ce946800\cxx\tools\__windows_compiler_wrapper__\windows_compiler_wrapper.py", line 54, in main
        arguments.extend(find_msvc_includes(compiler_real))
      File "D:\a\cxx\cxx\buck-out\v2\gen\prelude\fb50fd37ce946800\cxx\tools\__windows_compiler_wrapper__\windows_compiler_wrapper.py", line 37, in find_msvc_includes
        raise FileNotFoundError("{} not found".format(compiler))
    FileNotFoundError: cl.exe not found