Undo one needless_lifetimes change
    error[E0261]: use of undeclared lifetime name `'i`
       --> gen/lib/src/gen/include.rs:178:39
        |
    178 |     fn extend<I: IntoIterator<Item = &'i Include>>(&mut self, iter: I) {
        |                                       ^^ undeclared lifetime
        |
        = note: for more information on higher-ranked polymorphism, visit https://doc.rust-lang.org/nomicon/hrtb.html
    help: consider making the bound lifetime-generic with a new `'i` lifetime
        |
    178 |     fn extend<I: for<'i> IntoIterator<Item = &'i Include>>(&mut self, iter: I) {
        |                  +++++++
    help: consider introducing lifetime `'i` here
        |
    178 |     fn extend<'i, I: IntoIterator<Item = &'i Include>>(&mut self, iter: I) {
        |               +++
    help: consider introducing lifetime `'i` here
        |
    177 | impl<'i, 'a> Extend<&Include> for Includes<'a> {
        |      +++