Turn on exception handling for Buck on Windows
Without this one of the tests is going to abort instead of throw.

> Error: rust::Vec index out of range. Aborting.