Add regression test of issue 857
This currently fails to compile.

    error: `extern` block uses type `String`, which is not FFI-safe
       --> tests/ffi/lib.rs:329:34
        |
    329 |     impl CxxVector<SharedString> {}
        |                                  ^^ not FFI-safe
        |
    note: the lint level is defined here
       --> tests/ffi/lib.rs:23:1
        |
    23  | #[cxx::bridge(namespace = "tests")]
        | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        = help: consider adding a `#[repr(C)]` or `#[repr(transparent)]` attribute to this struct
        = note: this struct has unspecified layout
        = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)